producer:
    css: 'div#bylineInfo_feature_div.feature div.a-section'
    type: Text
asin:
    css: 'div.column.col2 div.section:nth-of-type(1)'
    type: Text
rankings:
    css: 'tr#SalesRank td.value'
    type: Text

